language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json

  # Run composer
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs

  # Additional PHP 5.3 config
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.3.3" ]; then phpenv config-add travis.php.ini; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.3" ]; then phpenv config-add travis.php.ini; fi;'

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
